### ISSUE TITLE
Add BioLink Model Based Resolver

### ISSUE THREAD

**Issue by kevinxin90** [biothings/biomedical_id_resolver.js#33]
When user supply a valid BioLink class and a corresponding ID, e.g.:
```
{
    "NamedThing": ["UMLS:1234"]
}
```
1. We will traverse the BioLink Class Hierarchical tree, find all descendants of NamedThing
2. Loop through all descendants, and check if "UMLS" is a valid ID_PREFIX of that class.
3. If not, skip the descendant
4. If yes, add the type and id to the resolver input, e.g. let's assume Disease, Gene, Phenotypic are descendants of NamedThing and have ID_PREFIX UMLS. So the updated input would be as follow:
```
{
    "NamedThing": ["UMLS:1234"],
    "Disease": ["UMLS:1234"],
    "PhenotypicFeature": ["UMLS:1234"],
    "Gene": ["UMLS:1234"]
}
```
5. Query APIs using existing config and infrastructure.
6. If semantic type/ID pair is part of the config and query returns hit, we will create a ValidEntity based on the response.
7. If semantic type/ID pair is not part of the config, we will create a UnresolvedEntity based on the input.
8. If semantic type/ID pair is part of the config, but query returns no hit, we will exclude it in the results.

**Comment by kevinxin90** [comment]
Changes on Validator Component:

1. Create a Based Validator Abstract Class, which both Default Validator and Biolink Based Validator will inherit from.
2. Logics for BioLink Based Validator
- [ Check if all semantic types are defined in BioLink model, if not, remove it from the list. ]
- [ If semantic type is undefined, use NamedThing instead ]
- [ For values of each semantic type, group based on prefix ]
- [ For each semantic type/prefix, check if its descendants has the prefix, if the descendant is within the config, add to the valid, if not, add to invalid ]

**Comment by colleenXu** [comment]
closing since likely defunct
