### ISSUE TITLE
Fix and update tests with the BioLink v2.1 changes

### ISSUE THREAD

**Issue by newgene** [biothings/biomedical_id_resolver.js#72]
As part of this parent issue: https://github.com/biothings/BioThings_Explorer_TRAPI/issues/207, we should fix and update the tests corresponding with the updates to BioLink v2.1.

**Comment by newgene** [comment]
`main` branch - all tests pass
`biolinkv2.1.0-updates-only` - currently 4 failed tests:

```
Test Suites: 2 failed, 8 passed, 10 total
Tests:       4 failed, 2 skipped, 101 passed, 107 total
```

@colleenXu please help add expected BioLink v2.1 compatible (entity names) tests as well.

**Comment by colleenXu** [comment]
@newgene please check the new branch biolink_v2.1 since that branch has been deleted.

**Comment by newgene** [comment]
I reran the tests using the latest `biolink_v2.1` branch, all tests pass now:

```
npm run git checkout "biolink_v2.1"
npm run compile
npm run test --workspace=biomedical_id_resolver

Test Suites: 10 passed, 10 total
Tests:       107 passed, 107 total
Snapshots:   0 total
Time:        32.605 s
```
